### ISSUE TITLE
stop mailman spam

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-chef#212]
we need to add SUBSCRIBE_FORM_SECRET = "<random string here>"  to stop mailman spam.

More info here.

Tried it manually it worked and stopped 200+ signups a day. Chef will kill it though so need to add it into the recipes.

https://www.ralfj.de/blog/2018/06/02/mailman-subscription-spam.html

**Comment by irabinovitch** [comment]
Until this is completed I'm going to pause chef on the mailman servers.  Feel free to resume it once this is complete.

**Comment by irabinovitch** [comment]
Looks like someone unpaused chef on the mail server without passing this config in. @jaymzh

**Comment by irabinovitch** [comment]
42 sign up attempts a day various spam bots on scale-planning today.

**Comment by irabinovitch** [comment]
we're up to a few hundred spam sign up attempts week per list now.  hope we can do this soon.

**Comment by irabinovitch** [comment]
Just deleted about 3000 spam signups from scale-design. Would be great to fix this.

**Comment by jaymzh** [comment]
"I turned off the engine because I didn't like the humming" :roll_eyes: 

It would have taken you exactly as long to add the same line to https://github.com/socallinuxexpo/scale-chef/blob/master/cookbooks/scale_mailman/templates/default/mm_cfg.py.erb as it would have to add it to the live server.

Also - from that article setting it to `""` doesn't seem like the right thing, you'd want to set it to a random string?

Anyway - feel free to send a one-line patch if you'd like. Otherwise next time I have a moment I'll dig into the implications and set this up.

**Comment by jaymzh** [comment]
I will point out, you wrote that cookbook even:  https://github.com/socallinuxexpo/scale-chef/pull/23

**Comment by irabinovitch** [comment]
Correct you need to set a random string. Hopefully someone from the infra team can get to this eventually and then we can start letting mailing list members join again.

**Comment by irabinovitch** [comment]
ping?

**Comment by jaymzh** [comment]
If only you'd just opened the file you wrote to make the exact same change, it would have been done with half the work you've put into this. Anyway, PR coming.
